// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpALvOD_B6Gli9pZzEOQPBrgIt-hsq66o',
    appId: '1:1004760536093:web:7df0cfe672e1ad59d762f4',
    messagingSenderId: '1004760536093',
    projectId: 'mjwm-36c0f',
    authDomain: 'mjwm-36c0f.firebaseapp.com',
    storageBucket: 'mjwm-36c0f.appspot.com',
    measurementId: 'G-YDCR58BLSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJi0fkFvPqQ4N7vDqus03KRjP6N3YICs4',
    appId: '1:1004760536093:android:de0bd7da1078de0bd762f4',
    messagingSenderId: '1004760536093',
    projectId: 'mjwm-36c0f',
    storageBucket: 'mjwm-36c0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZlIgGFUIdp0Qm1-lJsArfCau6l6ujTI',
    appId: '1:1004760536093:ios:a9956022e0e653b1d762f4',
    messagingSenderId: '1004760536093',
    projectId: 'mjwm-36c0f',
    storageBucket: 'mjwm-36c0f.appspot.com',
    iosBundleId: 'com.example.mjworkmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVZlIgGFUIdp0Qm1-lJsArfCau6l6ujTI',
    appId: '1:1004760536093:ios:a9956022e0e653b1d762f4',
    messagingSenderId: '1004760536093',
    projectId: 'mjwm-36c0f',
    storageBucket: 'mjwm-36c0f.appspot.com',
    iosBundleId: 'com.example.mjworkmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpALvOD_B6Gli9pZzEOQPBrgIt-hsq66o',
    appId: '1:1004760536093:web:50fff9025c676b11d762f4',
    messagingSenderId: '1004760536093',
    projectId: 'mjwm-36c0f',
    authDomain: 'mjwm-36c0f.firebaseapp.com',
    storageBucket: 'mjwm-36c0f.appspot.com',
    measurementId: 'G-RQT7480LR8',
  );

}